{"uuid": "9ba1c5ae-28d6-41cf-b5dd-7fa2d38686af", "children": ["991e3a86-87f0-444f-909d-02e06c4536a5"], "befores": [{"name": "_xunit_setup_method_fixture_TestValidRegistrationRT", "status": "broken", "statusDetails": {"message": "AttributeError: 'str' object has no attribute 'capabilities'\n", "trace": "  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\_pytest\\python.py\", line 779, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\Захар\\Desktop\\AutoTest\\RosTelecom\\tests\\test_rt_authorization.py\", line 22, in setup\n    self.open()\n  File \"C:\\Users\\Захар\\Desktop\\AutoTest\\RosTelecom\\tests\\test_rt_authorization.py\", line 25, in open\n    self.driver = webdriver.Chrome(\n                  ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 51, in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 40, in get_path\n    msg = f\"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager.\"\n                                         ^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1694275506371, "stop": 1694275506371}], "start": 1694275506371, "stop": 1694275506395}