{"uuid": "61c32b9b-64b2-49c7-91a9-2c3ecfbc3402", "children": ["00e9e7d6-f67c-453f-b4a5-a3e4c8023fce"], "befores": [{"name": "_xunit_setup_method_fixture_TestValidRegistrationRT", "status": "broken", "statusDetails": {"message": "AttributeError: 'str' object has no attribute 'capabilities'\n", "trace": "  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\_pytest\\python.py\", line 779, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\Захар\\Desktop\\AutoTest\\RosTelecom\\tests\\test_rt_authorization.py\", line 22, in setup\n    self.open()\n  File \"C:\\Users\\Захар\\Desktop\\AutoTest\\RosTelecom\\tests\\test_rt_authorization.py\", line 25, in open\n    self.driver = webdriver.Chrome(\n                  ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 51, in __init__\n    self.service.path = DriverFinder.get_path(self.service, options)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Захар\\AppData\\Local\\Programs\\Python\\Python311-32\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 40, in get_path\n    msg = f\"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager.\"\n                                         ^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1694275457908, "stop": 1694275457908}], "start": 1694275457908, "stop": 1694275458049}